### ISSUE TITLE
添加个中文的修改版本觉得不错

### ISSUE THREAD

**Issue by ShenXuGongZi** [Continuities/adarkroom#213]
中文版本 可以存档到服务器~ 觉得挺方便的，换浏览器也不怕啦~
chinese version can be archived to the server

Go -> http://g.miaowu.asia/reg.php

**Comment by skj3gg** [comment]
I'm not 100% sure of everything you're saying so if I'm wrong in my assumptions, please let me know. 

I don't think we are interested in having a server save state or putting one language on a different server than the rest of the game, additionally, this version uses some things like color which is against the creative design choice made to be black and white.

We stopped pointing to other repositories last year because we want a consistent interface, experience, and control over the game that we present.

I have nothing against this site or what it's doing, but don't feel that we should add a link to it as part of our current package.

Thanks for the notice thought!

**Comment by chuglydude** [comment]
did the hidden joy stick work?

**Comment by skj3gg** [comment]
@chuglydude This is not the correct place to be asking this. Next time please open a new issue, or comment in an issue that is about the topic. To answer your question though, I have not received a pull request from you so I don't know how the joystick works.

**Comment by chuglydude** [comment]
sorry blake my mistake
